#!/usr/bin/env python3
"""
GeM Bid Compliance Verification Platform - Mock Portal Adapters (Schema 2)
IMPORTANT NOTICE:
All responses generated by this module are SIMULATED / MOCKED GOVERNMENT PORTAL INTEGRATIONS.
In production, these would connect to NIC/GSTN/EPFO/MCA21 Open APIs or Sandbox credentials.
They are clearly identified as simulated to prevent misrepresentation.
"""

import datetime

def get_simulated_portal_record(source, bidder_identifier, override_status=None):
    """
    Returns Schema 2: Portal Verification Record
    source: udyam_portal | gstn_portal | pan_itd | epfo | esic | mca21 | dpiit_startup | nsic | blacklist_registry
    """
    now_iso = datetime.datetime.utcnow().isoformat() + "Z"

    # Pre-canned realistic databases for various demo bidders
    # BID-101: Compliant MSME
    # BID-102: Gatekeeper Blocked (GSTIN suspended, Debarred)
    # BID-103: Small Proprietorship (EPFO N/A, MCA N/A, pending docs)
    # BID-104: High Risk Debarred

    data_store = {
        # Compliant MSME: Bharat Tech Solutions Pvt Ltd
        "BID-101": {
            "blacklist_registry": {
                "source": "blacklist_registry",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_blacklisted": False,
                    "debarred_by": None,
                    "debarment_reason": None,
                    "debarred_until": None,
                    "incident_history_count": 0,
                    "registry_verified": "GeM Central Incident & Debarment Repository (CIMS)"
                }
            },
            "pan_itd": {
                "source": "pan_itd",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "pan_number": "AABCB1234F",
                    "pan_status": "ACTIVE",
                    "entity_name_itd": "BHARAT TECH SOLUTIONS PRIVATE LIMITED",
                    "aadhaar_linked": True,
                    "itr_compliant": True,
                    "itr_filed_years": ["AY 2024-25", "AY 2023-24"],
                    "form_26as_turnover_cr": 14.8,
                    "sec_206ab_specified_person": False
                }
            },
            "gstn_portal": {
                "source": "gstn_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "gstin": "07AABCB1234F1Z5",
                    "gstin_status": "ACTIVE",
                    "registration_date": "2018-04-12",
                    "legal_name": "Bharat Tech Solutions Private Limited",
                    "trade_name": "Bharat Tech Solutions",
                    "taxpayer_type": "Regular",
                    "consecutive_non_filing_months": 0,
                    "gstr1_filed_up_to": "Jan 2026",
                    "gstr3b_filed_up_to": "Jan 2026",
                    "e_way_bill_blocked": False
                }
            },
            "udyam_portal": {
                "source": "udyam_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "udyam_registration_number": "UDYAM-DL-01-0012345",
                    "enterprise_name": "Bharat Tech Solutions Private Limited",
                    "enterprise_type": "Small",
                    "major_activity": "Manufacturing & IT Services",
                    "nic_codes": ["62011", "26201"],
                    "date_of_incorporation": "2018-03-15",
                    "is_valid": True,
                    "social_category": "General",
                    "investment_in_plant_machinery_cr": 4.2,
                    "turnover_cr": 12.5
                }
            },
            "epfo": {
                "source": "epfo",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "establishment_code": "DLCPM0098765000",
                    "establishment_name": "BHARAT TECH SOLUTIONS PVT LTD",
                    "is_registered": True,
                    "status": "ACTIVE",
                    "active_members_count": 48,
                    "last_ecr_month": "Jan 2026",
                    "challans_paid_regularly": True,
                    "defaulter_flag": False
                }
            },
            "esic": {
                "source": "esic",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "employer_code": "11000987650001001",
                    "is_registered": True,
                    "covered_employees": 32,
                    "last_contribution_period": "Dec 2025 - Jan 2026",
                    "compliance_status": "COMPLIANT"
                }
            },
            "mca21": {
                "source": "mca21",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "cin_llpin": "U72200DL2018PTC334567",
                    "company_name": "BHARAT TECH SOLUTIONS PRIVATE LIMITED",
                    "roc_status": "ACTIVE",
                    "roc_name": "ROC Delhi",
                    "class_of_company": "Private",
                    "date_of_incorporation": "2018-03-15",
                    "paid_up_capital_inr": 5000000,
                    "last_agm_date": "2025-09-28",
                    "balance_sheet_date": "2025-03-31"
                }
            },
            "dpiit_startup": {
                "source": "dpiit_startup",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_recognized": False,
                    "dipp_number": None,
                    "status": "NOT_APPLIED"
                }
            },
            "nsic": {
                "source": "nsic",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_registered": True,
                    "certificate_number": "NSIC/DEL/GP/2023/0091",
                    "valid_until": "2027-03-31",
                    "monetary_limit_lakhs": 250
                }
            }
        },

        # BID-102: Gatekeeper Failures (GSTIN Suspended, Debarment Listed)
        "BID-102": {
            "blacklist_registry": {
                "source": "blacklist_registry",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_blacklisted": True,
                    "debarred_by": "Ministry of Railways / Western Railway Vigilance",
                    "debarment_reason": "Submission of forged OEM authorization certificate in tender WR/2024/991",
                    "debarred_until": "2027-11-30",
                    "incident_history_count": 3,
                    "registry_verified": "GeM Debarment Blacklist DB"
                }
            },
            "pan_itd": {
                "source": "pan_itd",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "pan_number": "AAACA8888P",
                    "pan_status": "ACTIVE",
                    "entity_name_itd": "APEX INFRA AND SUPPLIES LLP",
                    "aadhaar_linked": True,
                    "itr_compliant": False,
                    "itr_filed_years": ["AY 2022-23"],
                    "sec_206ab_specified_person": True
                }
            },
            "gstn_portal": {
                "source": "gstn_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "gstin": "27AAACA8888P1Z3",
                    "gstin_status": "SUSPENDED",
                    "registration_date": "2020-01-15",
                    "cancellation_date": "2025-10-01 (Suo-motu Rule 21A notice)",
                    "legal_name": "Apex Infra & Supplies LLP",
                    "taxpayer_type": "Regular",
                    "consecutive_non_filing_months": 5,
                    "gstr1_filed_up_to": "Aug 2025",
                    "gstr3b_filed_up_to": "Aug 2025",
                    "e_way_bill_blocked": True
                }
            },
            "udyam_portal": {
                "source": "udyam_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "udyam_registration_number": "UDYAM-MH-02-0087612",
                    "enterprise_name": "Apex Infra & Supplies LLP",
                    "enterprise_type": "Medium",
                    "is_valid": True
                }
            },
            "epfo": {
                "source": "epfo",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "establishment_code": "MHBAN0087654000",
                    "is_registered": True,
                    "status": "DEFAULT",
                    "active_members_count": 28,
                    "challans_paid_regularly": False,
                    "defaulter_flag": True
                }
            },
            "mca21": {
                "source": "mca21",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "cin_llpin": "AAJ-8761",
                    "company_name": "APEX INFRA AND SUPPLIES LLP",
                    "roc_status": "ACTIVE",
                    "roc_name": "ROC Mumbai"
                }
            }
        },

        # BID-103: Small Proprietorship (EPFO N/A, MCA N/A, Low Confidence OEM)
        "BID-103": {
            "blacklist_registry": {
                "source": "blacklist_registry",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_blacklisted": False,
                    "debarred_by": None,
                    "incident_history_count": 0
                }
            },
            "pan_itd": {
                "source": "pan_itd",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "pan_number": "BPWPS5544K",
                    "pan_status": "ACTIVE",
                    "entity_name_itd": "SURESH SHARMA (PROP. SHREE GANESH ENTERPRISES)",
                    "aadhaar_linked": True,
                    "itr_compliant": True,
                    "itr_filed_years": ["AY 2024-25", "AY 2023-24"],
                    "sec_206ab_specified_person": False
                }
            },
            "gstn_portal": {
                "source": "gstn_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "gstin": "06BPWPS5544K1ZR",
                    "gstin_status": "ACTIVE",
                    "registration_date": "2021-08-10",
                    "legal_name": "Suresh Sharma",
                    "trade_name": "Shree Ganesh Enterprises",
                    "taxpayer_type": "Regular",
                    "consecutive_non_filing_months": 0,
                    "gstr1_filed_up_to": "Jan 2026",
                    "gstr3b_filed_up_to": "Jan 2026"
                }
            },
            "udyam_portal": {
                "source": "udyam_portal",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "udyam_registration_number": "UDYAM-HR-03-0044551",
                    "enterprise_name": "Shree Ganesh Enterprises",
                    "enterprise_type": "Micro",
                    "is_valid": True
                }
            },
            "epfo": {
                "source": "epfo",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_registered": False,
                    "note": "Exempted / Below 20 employees statutory ceiling"
                }
            },
            "mca21": {
                "source": "mca21",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "note": "Sole proprietorship - Not registered under Companies Act"
                }
            },
            "dpiit_startup": {
                "source": "dpiit_startup",
                "is_mocked": True,
                "disclaimer": "SIMULATED / MOCKED DATA - Not live API",
                "retrieved_fields": {
                    "is_recognized": True,
                    "dipp_number": "DIPP99412",
                    "status": "VALID_STARTUP",
                    "valid_until": "2028-08-01"
                }
            }
        }
    }

    bidder_data = data_store.get(bidder_identifier, data_store["BID-101"])
    portal_data = bidder_data.get(source, {
        "source": source,
        "is_mocked": True,
        "disclaimer": "SIMULATED / MOCKED DATA - Default fallback",
        "retrieved_fields": {}
    })

    record_status = override_status if override_status else "success"

    return {
        "record_id": f"REC-MOCK-{source[:4].upper()}-{bidder_identifier}",
        "bidder_id": bidder_identifier,
        "source": source,
        "retrieved_fields": portal_data.get("retrieved_fields", {}),
        "query_status": record_status,
        "queried_at": now_iso,
        "is_mocked_simulation": True,
        "simulation_notice": "SIMULATED MOCK ADAPTER - For prototyping only. Not connected to live Gov APIs."
    }

def get_all_simulated_portals_for_bidder(bidder_identifier):
    sources = [
        "blacklist_registry",
        "pan_itd",
        "gstn_portal",
        "udyam_portal",
        "epfo",
        "esic",
        "mca21",
        "dpiit_startup",
        "nsic"
    ]
    return [get_simulated_portal_record(s, bidder_identifier) for s in sources]

if __name__ == "__main__":
    records = get_all_simulated_portals_for_bidder("BID-101")
    import json
    print(json.dumps(records, indent=2))
